### ISSUE TITLE
PostgresSQL support

### ISSUE THREAD

**Issue by 1988gadocansey** [referbruv/ContainerNinja.CleanArchitecture#41]
I've tried adding dbconnection using postgres but it is not working. In the service.cs ive added the below

 services.AddDbContext<DbContext>(options =>
                options.UseNpgsql(
                    Configuration.GetConnectionString("DefaultConnection")));

Unhandled exception. System.ArgumentException: Connection string keyword 'server' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)

**Comment by referbruv** [comment]
Hey @1988gadocansey, thanks for sharing! Lemme check and get back.

**Comment by referbruv** [comment]
@1988gadocansey the boilerplate as is, supports SQLite which is injected in this file here: 

https://github.com/referbruv/ContainerNinja.CleanArchitecture/blob/master/API/ContainerNinja.Infrastructure/ServiceExtensions.cs

`
private static IServiceCollection AddDatabaseContext(this IServiceCollection services, IConfiguration configuration)
        {
            return services.AddSqlite<DatabaseContext>(configuration.GetConnectionString("DefaultConnection"), (options) =>
            {
                options.MigrationsAssembly("ContainerNinja.Migrations");
            });
        }
`

Just remove this code and add Postgres:

`
services.AddDbContext(options =>
  options.UseNpgsql(
  Configuration.GetConnectionString("DefaultConnection")));
`

Finally update the DefaultConnection accordingly with the Postgres connection string.

This should get things working for you. If not, just let me know.

**Comment by 1988gadocansey** [comment]
Thanks for the support
